# DuckDB config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('MELTANO_ENVIRONMENT', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      threads: 4
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      external_root: /tmp/data_catalog/conformed
    staging:
      type: duckdb
      threads: 4
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      external_root: /tmp/data_catalog/conformed
    prod:
      type: duckdb
      threads: 4
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      external_root: /tmp/data_catalog/conformed
